### ISSUE TITLE
DOMException on some pages due to invalid selectors

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5959] opened 2019-10-10 12:54 UTC
E.g. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout

Error:
```
DOMException: "'#Track_sizing_and_minmax() ~ pre[class*=html], #Track_sizing_and_minmax() ~ * pre[class*=html]' is not a valid selector"
```

**Comment by peterbe** [comment] 2019-10-10 12:55
Same error here: https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

**Comment by peterbe** [comment] 2019-10-10 13:00
The curious thing is that the error is "caused" by HTML like this:
```html
<h3 id="capitalize_(General)" name="capitalize_(General)"><code>capitalize</code> (General)</h3>
```
But if you go to https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/text-transform and, when logged in, and Shift refresh the new HTML becomes:
```html
<h3 id="capitalize_General" name="capitalize_(General)"><code>capitalize</code> (General)</h3>
```

which the React code should be able to cope with.

**Comment by peterbe** [comment] 2019-10-10 13:00
After having done that, https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform now works.

**Comment by peterbe** [comment] 2019-10-10 14:20
Some pages just need to be re-rendered (on the wiki) and then they work. 
Other pages don't work. Like this Korean page: https://developer.mozilla.org/ko/docs/Web/CSS/linear-gradient
I think it's failing because of the non-ascii characters in the DOM ID.

**Comment by peterbe** [comment] 2019-10-10 14:22
Oops! Didn't mean to press the close button.

**Comment by schalkneethling** [comment] 2019-10-10 14:28
> Some pages just need to be re-rendered (on the wiki) and then they work.

Yup, I have seen that as well. Wonder if we can kick-off a re-render of all the pages. Should solve the majority of the errors no?

**Comment by peterbe** [comment] 2019-10-10 14:33
> Wonder if we can kick-off a re-render of all the pages. Should solve the majority of the errors no?

I think we should do that. But it won't solve all pages. E.g. [this Korean page](https://developer.mozilla.org/ko/docs/Web/CSS/linear-gradient)

**Comment by peterbe** [comment] 2019-10-10 14:43
Another page where it doesn't help to re-render: https://developer.mozilla.org/zh-CN/docs/Web/CSS/linear-gradient

**Comment by peterbe** [comment] 2019-10-10 15:26
The ACTUAL solution is a bit more non-trivial but perhaps worth persuing sooner rather than later. The code that takes the `<h3>` content and "slugifies" it should also do something like `text.replace(/^\d+/g, '')` but what happens if the HTML input was `<h3>1234</h3>` then you'd get `<h3 id="">1234</h3>`.

**Comment by peterbe** [comment] 2019-10-10 15:40
Also, if you just remove leading digits from the generated ID, you could cause non-distinct IDs. E.g. 
```html
<h3>1 Cat</h3>
<h3>2 Cat</h3>
```
would become
```html
<h3 id="Cat">1 Cat</h3>
<h3 id="Cat">2 Cat</h3>
```

To solve that, a better solution might be something like this:
```javascript
header.id = slugify(header.textContent.replace(/^\d+/g, 'n'));
```
Then you'd get:
```html
<h3 id="n1_Cat">1 Cat</h3>
<h3 id="n2_Cat">2 Cat</h3>
```

**Comment by tobinmori** [comment] 2019-10-10 20:00
@peterbe won't that just bluntly replace 1+ starting numbers with an 'n'?

Maybe something kinda like?
```
var re = /(\d+)(.*)/;
header.id = slugify(header.textContent.replace(re, 'n$1$2'));
```

**Comment by escattone** [comment] 2019-10-10 20:09
I wrote a one-off script to re-render all 381 pages listed in Google Analytics, and ran it. The script included CDN invalidations, so hopefully the re-rendered pages would be picked-up immediately. Of course, this only resolves the issue some of the pages.

**Comment by peterbe** [comment] 2019-10-11 15:22
Re-render only solves the problem with those ancient docs that allowed control characters in the ID. It doesn't solve the problem with IDs that start with a digit.

**Comment by peterbe** [comment] 2019-10-11 15:25
@tobinmori Your response isn't wrong but I wrote the wrong pseudo code. What I implemented, in Python, was this:
```python
if slug[0].isdigit():
    slug = 'id' + slug
```

**Comment by escattone** [comment] 2019-10-11 21:03
There is another class of errors as well. Today I fixed https://developer.mozilla.org/fr/docs/Web/CSS/filter. The issue wasn't due to something that we currently clean-up via the code. It used `div` elements with `id`s containing `(` and `)`, like `id="blur()"`, which were in turn referenced by `EmbedLiveSample` calls, like `EmbedLiveSample("blur()", ...)`. I manually edited the content to make it match the English version which uses `id="blur_example"` and `EmbedLiveSample("blur_example", ...)`.

In this case, when saving a new revision (which stores the raw HTML), we might want to consider looking for `EmbedLiveSample` macro calls where the first argument (an `id`) contains illegal characters and clean both the `id` used as the argument to the macro call and the actual `id` on the HTML element (in this case, a `div`).

**Comment by escattone** [comment] 2019-10-11 21:15
I fixed https://developer.mozilla.org/de/docs/Web/CSS/content manually as well. It was in the same class of errors as described immediately above. However, in this case the `id` that was causing an error [here](https://github.com/mozilla/kuma/blob/8e094c909c4444e6245b2f8419ddd549dd02bbcd/kuma/javascript/src/live-examples.js#L51) was `Code_sample_-_adding_an_icon_after_text.`, and in particular it was the `.` character at the end.

**Comment by escattone** [comment] 2019-10-11 21:25
https://developer.mozilla.org/ko/docs/CSS3_Columns belongs in that class as well. Again, this class is defined by the fact that our current `injectSectionIDs()` Python code doesn't process `id`s on `div` tags.

**Comment by escattone** [comment] 2019-10-11 21:44
https://developer.mozilla.org/pt-BR/docs/Web/CSS/:checked belongs in the original class, because the `id` is on a tag (`h3`) that is processed by `injectSectionIDs()`, but isn't addressed by #5960 since the offending characteristic of the `id` of the `h3` tag is that it ends in a period (in this case `Usando_checkboxes_escodindos_para_amarzenar_algum_valor_booleano.`). Also, this is another case where the HTML element with the offending `id` is paired with a call to the `EmbedLiveSample` macro (in this case `EmbedLiveSample("Usando_checkboxes_escodindos_para_amarzenar_algum_valor_booleano.", ...)`. I fixed this one manually as well.

**Comment by escattone** [comment] 2019-10-11 22:23
Fixed https://developer.mozilla.org/ja/docs/Web/Guide/CSS/Using_multi-column_layouts manually. It belongs in that class where the live samples use `id`s on `div`s rather than `h1`-`h6` tags.

**Comment by escattone** [comment] 2019-10-11 22:56
Fixed https://developer.mozilla.org/fr/docs/Web/CSS/imagefunction manually. It was another `EmbedLiveSample` case that used an `h3` tag with an offending `id` (`id="Afficher_une_partie_(sprite)"`) referenced in the call to `EmbedLiveSample` (`EmbedLiveSample("Afficher_une_partie_(sprite)", ...)`. The `id` of the `h3` tag is cleaned to `"Afficher_une_partie_sprite"`, but the query code in `live-examples.js` uses `"Afficher_une_partie_(sprite)"` (which it gets from the `id` extracted from the `iframe` `id`, which is generated from the argument to `EmbedLiveSample`, which is not cleaned) and bombs.

So this class of live samples, that contain the live sample code (HTML, CSS, etc.) within header tags (`h1`-`h6`), could be cleanly handled by replicating whatever cleaning steps we do in `injectSectionIDs()` (within the `slugify` method) within `live-examples.js`. What that won't handle are all of the cases where the live sample code is contained within non-header tags (like `div`s), since the `id` of the `div` tags wouldn't be cleaned, but the `id` within `live-examples.js` would.

**Comment by escattone** [comment] 2019-10-12 00:24
I've spent almost the entire the day looking at over 150 of the documents that had reported rendering errors to GA since we launched the `beta` domain, just to get a better idea of the context here. I think the only part of #5960 I feel certain about is the `try-except` wrapper around the `id`-based DOM queries in `live-examples.js`. I'm not sure if anything else is worth the effort. It may be, but I'm not sure.

#5960 will only partially handle a subset of the errors, specifically those that were caused by bad `id`s used for live samples where the container housing the sample code (HTML, CSS, etc.) is a header tag (`h1`-`h6`).

I say "partially handle" because we'd also have to modify the `EmbedLiveSample` macro such that we clean its first argument (the `id`) using a JS version of the same `slugify` function we use in Python. We need to do that so that the [`src` URL for the `iframe` that the macro generates](https://github.com/mdn/kumascript/blob/ee1307feacccb57254456bb2cbe9893e37c31ff3/macros/EmbedLiveSample.ejs#L35) matches the cleaned `id` in the HTML. So does that mean we now have that `slugify` code replicated in 3 places: the Python code, a new Kuma JS copy for use within `live-example.js`, and another Kumascript JS copy for use within `EmbedLiveSample.ejs`? That feels ugly.

Also, even if we commit to that effort, it won't handle another subset of bad, live-sample-related `id` errors, the ones where the container housing the live sample code is **not** a header tag, for example a `div` tag, which has been common among those errors I've seen today. It would be another chunk of work to add the post-render cleaning necessary to handle that subset of errors. I suppose we'd have to look for live-sample `iframes` (ones with `id="section_..."` **and** a `src` attribute that is a code sample URL) and then clean the `id` on the `iframe` as well as the extracted `id` on the containing HTML element?

A lower-effort alternative to all of this, I think, would be to merge a new PR with just the `try-except` wrapper around the `id`-based DOM queries in `live-examples.js`, and then simply manually fix the content of the remaining documents with rendering errors. Then we go brew a cup of tea and go back to thinking about Stumptown! 🍵 😄

**Comment by schalkneethling** [comment] 2019-10-14 08:15
Phew, that is a *ton* of work done by you all. Thanks so much, @peterbe and @escattone

**Comment by atopal** [comment] 2019-10-14 11:07
@escattone agreed, we can fix the remaining ones manually, and with the try-except wrapper only the iframes would be broken, right? And if so, they were already broken before?

**Comment by atopal** [comment] 2019-10-14 11:11
Never mind, I misunderstood, the live sample iframes are currently not broken.

**Closed** 2019-10-14 23:27 UTC
Labels: p1, type: bug
