### ISSUE TITLE
Revisions dashboard isn't working on autocomplete lookups

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5745] opened 2019-09-04 10:46 UTC
We used to have a possible DDoS on the AJAX endpoints that the [revision dashboard](https://developer.mozilla.org/en-US/dashboards/revisions) uses. We fixed that in [1573233](https://bugzilla.mozilla.org/show_bug.cgi?id=1573233). But I guess we failed to test it properly because now it appears as if I have to sign in even though I'm already signed in. 
<img width="1503" alt="Screen Shot 2019-09-04 at 6 36 12 AM" src="https://user-images.githubusercontent.com/26739/64248607-94bdb400-cedf-11e9-832e-4731e9eb4a01.png">
Also, the jQuery code attempts to read the response even though it's not JSON (it was a 302 redirect).

**Comment by peterbe** [comment] 2019-09-04 11:32
Unable to reproduce this locally :(

**Comment by peterbe** [comment] 2019-09-04 11:34
@escattone Any idea? I know I'm logged in. I can see that my session cookie is included in the XHR request. It uses the `@login_required` which means it's enough to just be `.is_authenticated`.

**Comment by escattone** [comment] 2019-09-04 17:04
@peterbe I wasn't able to reproduce it locally either, but I noticed that it works fine if I use the wiki endpoint directly (https://wiki.developer.mozilla.org/en-US/dashboards/revisions). I strongly suspect that something is wrong with the configuration of one of the CDN behaviors. I'll check into that.

**Comment by escattone** [comment] 2019-09-04 17:16
@peterbe This is fixed. The problem was that the stage/prod CDN's `*/dashboards/topic_lookup` and `*/dashboards/user_lookup` behaviors were not originally designed to forward the `sessionid` cookie (since those endpoints did not originally require login). That has been corrected, and I've verified that the changes have completely fixed this issue. Thanks for noticing this @peterbe!

**Comment by escattone** [comment] 2019-09-04 17:22
Re-opening since I need to create an infra PR to update the Terraform for the primary CDN.

**Comment by escattone** [comment] 2019-09-04 17:42
@limed (with perhaps a bit of help from me) is going to do a complete update of our Terraform for the CDN's so it matches reality, but we're going to wait until after the beta launch since the primary stage/prod CDN behaviors will change radically (see https://github.com/mdn/sprints/issues/1645). So I'm closing this since https://github.com/mdn/sprints/issues/1645 will cover the update of the Terraform sometime in the near future.

**Closed by escattone** 2019-09-04 17:42 UTC
